In [ ]:
import  numpy as np

In [87]:
# Create zero matrix 5x5 than set every second element equal 1. First element always 0
def get_chess(a):
    field = np.zeros((a,a)) 
    field[::2, 1::2] = 1
    field[1::2, ::2] = 1
    return field


In [88]:
print(get_chess(8))

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
# Function receive array shuffle it with random seed and return this seed and shuffled array.
def shuffle_seed(array):
    seed = np.random.randint(2**32 - 1)
    np.random.seed(seed)
    shuffled_array = np.random.permutation(array)
    return (shuffled_array, seed)

In [124]:
array = [1, 2, 3, 4, 5]
print(shuffle_seed(array))
print(array)
# (array([1, 3, 2, 4, 5]), 2332342819)
# print(shuffle_seed(array))
# (array([4, 5, 2, 3, 1]), 4155165971)

(array([2, 5, 1, 3, 4]), 2146820815)
[1, 2, 3, 4, 5]
